E2Helper.Descriptions["pxOpenMedia(s)"] = 		"Opens the URL on the current PlayX player if you're permitted\nUrl"
E2Helper.Descriptions["pxOpenMedia(ss)"] =		"Opens the URL on the current PlayX player if you're permitted\nUrl,Provider (empty string for autodetect)"
E2Helper.Descriptions["pxOpenMedia(ssn)"] = 	"Opens the URL on the current PlayX player if you're permitted\nUrl,Provider (empty string for autodetect),Start-time in seconds"
E2Helper.Descriptions["pxOpenMedia(ssnn)"] = 	"Opens the URL on the current PlayX player if you're permitted\nUrl,Provider (empty string for autodetect),Start-time in seconds,forceLowFramerate (0 default)"
E2Helper.Descriptions["pxOpenMedia(ssnnn)"] = 	"Opens the URL on the current PlayX player if you're permitted\nUrl,Provider (empty string for autodetect),Start-time in seconds,forceLowFramerate (0 default),useJW (1 default)"
E2Helper.Descriptions["pxOpenMedia(ssnnnn)"] = 	"Opens the URL on the current PlayX player if you're permitted\nUrl,Provider (empty string for autodetect),Start-time in seconds,forceLowFramerate (0 default),useJW (1 default),ignoreLength (no use atm?!)"

E2Helper.Descriptions["pxURI"] = 		"Returns the URI of the media currently playing"
E2Helper.Descriptions["pxURL"] = 		"Returns the URLof the media currently playing"
E2Helper.Descriptions["pxStopMedia"] =	"Stops the media completly"
E2Helper.Descriptions["pxSpawn()"] = 		"Spawns a playX player at the owner's aimpos"
E2Helper.Descriptions["pxSpawn(n)"] = 		"Spawns a playX player or playX repeater at the owner's aimpos."
E2Helper.Descriptions["pxSpawn(sn)"] = 		"Spawns a playX player or playX repeater at the owner's aimpos. S is the model of the player. Default: \"models/dav0r/camera.mdl\""
E2Helper.Descriptions["pxInstance()"] = 		"Returns the playX as entity"
E2Helper.Descriptions["pxRepeaters()"] = 		"Returns the playX repeater as array"
E2Helper.Descriptions["pxCurrentMedia"] = 		"Returns the data of the current video as a table.Same as the outputs of the playX"
